### ISSUE TITLE
Transparency Layer issue at the beginning of the Sunken Ghost Ship

### ISSUE THREAD

**Issue by princenb** [VitorVilela7/wide-snes#14]
Once inside the Ghost Ship, right before the Ghosts begin to appear, there is a horizontal band of grey transparency that's positioned in front of Mario instead of behind him. Checked my original cart and it's definitely different.

![Super Mario World (USA) SA-1 Widescreen v1 2-003](https://user-images.githubusercontent.com/25079240/122663878-78414900-d152-11eb-8185-7b158ac20b33.jpg)
![Super Mario World (USA) SA-1 Widescreen v1 2-004](https://user-images.githubusercontent.com/25079240/122663879-78d9df80-d152-11eb-87de-e4ce92220838.jpg)

**Comment by TheLX5** [comment]
The issue is also present on the original game:
![vanilla002](https://user-images.githubusercontent.com/17969056/122683137-32b46880-d1b2-11eb-8b1b-536653bca449.png)

It's related to how color substraction only works on certain palette rows on the SNES. Color substraction is used by the reappearing ghosts on the ship. 
You can see how red mushrooms and fire flowers also have their colors affected while the feather isn't during this area.

**Comment by princenb** [comment]
Ah you're right, I just tried an original Cart on a SuperNT and saw the same problem.

But using Vitor's 1.40 SA-1 patch, on a MiSTer system, it renders without the horizontal band for whatever reason. That's what I'd used to check before.

**Comment by VitorVilela7** [comment]
As LX5 pointed out, it also happens with the original game. Some systems may not have the same behavior depending on how they interpret color translucency.
