### ISSUE TITLE
Exact aspect ratio

### ISSUE THREAD

**Issue by aramaicus** [VitorVilela7/wide-snes#27]
Is it meant for 16×9 or for a slightly wider aspect ratio?

Using it with default settings I get very thin horizontal black bars.

Setting it on Retroarch from "core provided aspect ratio" to 16×9 works well but I am afraid if I am stretching the image.

**Comment by DerKoun** [comment]
The first version is intended for 16:9, with corrected pixel AR , i.e. stretched by 8:7.
However the width can only be increased in specific increments, so 16:9 cannot be hit perfectly.
Forcing it to 16:9 is recommended. It will actually reduce the stretching for PAR correction slightly. But it's so minor, it will look great.

The upcoming patch for 16:9 at 1:1 PAR will be exactly 16:9 with overscan disabled. (looses 4 liens at top an bottom.)
That will scale to exactly 1080p at 5x. So no stretching, but perfect integer scaling to a 100% filled 1080p 16:9 screen.

Until then don't be afraid to force 16:9. It's ideal.

**Comment by VitorVilela7** [comment]
Since version 1.10, I have included additional instructions in how to get different aspect ratios (AR) and pixel aspect ratio (PAR), which should answer your question. You can see the instructions and files on the [releases](https://github.com/VitorVilela7/wide-snes/releases) tab. Let me know if you have additional questions.
