### ISSUE TITLE
the bowser boss stage doesnt work well with widescreen

### ISSUE THREAD

**Issue by danielh05** [VitorVilela7/wide-snes#4]
https://user-images.githubusercontent.com/35849198/122615239-7a3ed580-d088-11eb-8fde-3b4f418aae76.mp4

**Comment by VitorVilela7** [comment]
Is the Bowser room decentered or is it a thing from the screen recorder?

Em sex, 18 de jun de 2021 17:57, daniela ***@***.***>
escreveu:

**Comment by danielh05** [comment]
thats just my screen recorder

**Comment by VitorVilela7** [comment]
This was a design decision, given that the Bowser scene suggests that we are on the top of the castle, which has limited horizontal space. Although it was possible to expand the scene in standard 16:9, it would be required to leave the scene partially cut on 21:9 version because of the sprite limits, given that the entire stage is rendered via Mode 7. Because of that, it was decided to keep the scene this. I understand it might not be what you thought initially and apologies if that's the case.

![image](https://user-images.githubusercontent.com/12776674/122857257-9479ed00-d2ee-11eb-97c2-b34271e6caf4.png)

**Comment by danielh05** [comment]
ah alright thats understandable, thanks for the response!
