### ISSUE TITLE
[Question] Does it work with Rom Hacks?

### ISSUE THREAD

**Issue by Toadfield** [VitorVilela7/wide-snes#5]
It would be wonderful if that would work.

**Comment by VitorVilela7** [comment]
As of this post date (June 22, 2021), ROM hacks can be made with Super Mario World Widescreen under the following options:

1) You must use this BPS patch, applied to the original game as base ROM;
2) Lunar Magic 3.30 or newer is required;
3) All resources must be compatible with SA-1 Pack v1.40 or newer;
4) You must disable the VRAM patch, available on Lunar Magic level options.

You are free to use SMW Widescreen as Base ROM, keeping in mind it might break with any other SMW hacking resource and even if importing assets from older ROM hacks, they might not work because of the widescreen resolution, Lunar Magic changes or SA-1 Pack changes.

**Comment by Toadfield** [comment]
I meant,can I apply this hack to any rom hacks that don't use it?

**Comment by VitorVilela7** [comment]
No, that will not work.

Em ter., 22 de jun. de 2021 às 00:51, Toadfield ***@***.***>
escreveu:

**Comment by Toadfield** [comment]
Is it possible to make that work in the future?

**Comment by VitorVilela7** [comment]
Not possible, each ROM hack will have to be redesigned with the widescreen
size in mind and updated resources. This can't be solved by just applying
the BPS patch over.

**Comment by Toadfield** [comment]
ok
